server:
  port: 9004


spring:
  application:
    name: User-Service
  data:
    mongodb:
      uri: mongodb://localhost:27017/user


#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    instance:
#      hostname: localhost

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400