server:  
  port: ${PORT:2222}

spring:  
  application:
    name: account-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: micro 
      password: micro

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
      
ribbon:
  eureka:
    enabled: true