server:
  port: 9003

spring:
  datasource:
    username: root
    url: jdbc:mariadb://localhost:3307/department
    password: 1998
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        hbm2ddl.auto: update

  application:
    name: Department-Service

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    instance:
#      hostname: localhost

