server:
  port: 9999

spring:
  application:
    name: api-gateway

  loadbalancer:
    ribbon:
      enabled: false


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-boot-microservice-realm


eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}




